[package]
name = "open_tv"
version = "1.5.2"
description = "Fast And Powerful IPTV App"
authors = ["Frédéric Lachapelle"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.80"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "open_tv_lib"
crate-type = ["staticlib", "cdylib", "lib"]

[build-dependencies]
tauri-build = { version = "2.0.4", features = [] }

[dependencies]
serde_json = "1.0"
rusqlite = { version = "0.32.1", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.2.0", features = ["tray-icon"] }
anyhow = { version = "1.0.95" }
regex = { version = "1.10.5", features = ["std"] }
directories = "5.0.1"
reqwest = "0.12.12"
tokio = { version = "1.43.0", features = ["full"] }
url = "2.5.4"
r2d2_sqlite = "0.25.0"
r2d2 = "0.8.10"
bytes = "1.9.0"
tauri-plugin-dialog = "2.2.0"
chrono = "0.4.39"
which = "7.0.1"
tauri-plugin-clipboard-manager = "2.2.0"
tauri-plugin-shell = "2.2.0"
simplelog = "0.12.2"
log = "0.4.22"
rusqlite_migration = "1.3.1"
base64 = "0.22.1"
tauri-plugin-notification = "2.2.0"
warp = "0.3.7"
if-addrs = "0.13.3"
[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
shell-words = "1.1.0"
[target.'cfg(target_os = "windows")'.dependencies]
winsplit = "0.1.0"
[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-single-instance = "2.2.0"
