[package]
name = "open_tv"
version = "0.1.0"
description = "A Tauri App"
authors = ["Frédéric Lachapelle"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.80"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "open_tv_lib"
crate-type = ["staticlib", "cdylib", "lib"]

[build-dependencies]
tauri-build = { version = "2.0.0-beta.19", features = [] }

[dependencies]
serde_json = "1.0"
rusqlite = { version = "0.32.0", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.0.0-beta.24", features = [] }
anyhow = { version = "1.0.86" }
regex = { version = "1.10.5", features = ["std"] }
directories = "5.0.1"
