name: Build and Upload for Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build Angular App
      working-directory: ./ng-open-tv
      run: |
        npm install
        npm run prod
        
    - name: Build Electron app
      working-directory: ./electron-open-tv
      run: |
        npm install
        npm run publish
        
    - name: Upload Squirrel Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: open-tv-windows-squirrel-amd64
        path: ./electron-open-tv/out/make/squirrel.windows/x64/*.exe
        retention-days: 90
      
